CREATE DATABASE Aeroporti_ex4_M3;

USE Aeroporti_ex4_M3;

CREATE TABLE Aeroporto(
	Città VARCHAR(255),
	Nazione VARCHAR(255),
	NumPiste VARCHAR(255)
);

ALTER TABLE Aeroporto CHANGE NumPiste NumPiste TINYINT UNSIGNED;
ALTER TABLE Aeroporto ADD CONSTRAINT PRIMARY KEY(Città);

CREATE TABLE Volo(
ID_Volo INT,
GiornoSett VARCHAR(255),
CittàPart VARCHAR(255),
OraPart VARCHAR(255),
CittàArr VARCHAR(255),
OraArr DATETIME,
TipoAereo VARCHAR(255)
);

ALTER TABLE Volo CHANGE ID_Volo ID_Volo CHAR(5);
ALTER TABLE Volo CHANGE OraPart OraPart TIME;
ALTER TABLE Volo CHANGE OraArr OraArr TIME;
ALTER TABLE Volo CHANGE GiornoSett GiornoSett ENUM("LUN","MAR","MER","GIO","VEN","SAB","DOM");
ALTER TABLE Volo ADD CONSTRAINT PRIMARY KEY(ID_Volo);
ALTER TABLE Volo ADD FOREIGN KEY(CittàPart) REFERENCES Aeroporto(Città) ON UPDATE CASCADE ON DELETE NO ACTION;
ALTER TABLE Volo ADD FOREIGN KEY(CittàArr) REFERENCES Aeroporto(Città) ON UPDATE CASCADE ON DELETE NO ACTION;

CREATE TABLE Aereo(
TipoAereo VARCHAR(255),
NumPasseggeri INT,
QtaMerci INT
);

ALTER TABLE Aereo CHANGE QtaMerci QtaMerci DOUBLE;
ALTER TABLE Aereo CHANGE NumPasseggeri NumPasseggeri SMALLINT UNSIGNED;
ALTER TABLE Aereo ADD CONSTRAINT PRIMARY KEY(TipoAereo);


